"""Generate a probing-robustness sweep config.

Emits a YAML where each transformer checkpoint is expanded across:
  * ``embed_source`` ∈ {encoder, decoder}
  * ``embed_layer`` ∈ {0 (post-embed), 1..n_layers (post-block i), -1 (post-norm)}

so the probing analysis runs once per (checkpoint, source, layer). Output is
written to ``src/analysis/configs/probing_robustness.yaml``.
"""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent

# Matches probing.yaml. Adjust if you retrain with a different n_layers.
N_LAYERS = 4
LAYERS = [-1, 0] + list(range(1, N_LAYERS + 1))  # post-norm, post-embed, then each block
SOURCES = ["encoder", "decoder"]

# (short_id, run_name, ckpt_dir, mode, full_label)
CKPTS = [
    ("enum_iw",   "wild-dawn-50",     "~/mlmp_checkpoints/no-rl-in-weight",            "in-weight",             "InWeight·Enum"),
    ("enum_es",   "revived-voice-51", "~/mlmp_checkpoints/no-rl-easy-symbol-shuffling", "easy-symbol-shuffling", "SymShuf·Enum"),
    ("enrl_iw",   "warm-dust-48",     "~/mlmp_checkpoints/in-weight",                   "in-weight",             "InWeight·EnumRL"),
    ("enrl_es",   "sandy-puddle-49",  "~/mlmp_checkpoints/easy-symbol-shuffling",       "easy-symbol-shuffling", "SymShuf·EnumRL"),
]


def _layer_tag(layer: int) -> str:
    return "post" if layer == -1 else f"L{layer}"


def main() -> None:
    method_entries: list[str] = []
    method_names: list[str] = []

    for ckpt_id, run_name, ckpt_dir, mode, full_label in CKPTS:
        for source in SOURCES:
            for layer in LAYERS:
                name = f"tx_{ckpt_id}_{source[:3]}_{_layer_tag(layer)}"
                label = f"{full_label} / {source[:3]}·{_layer_tag(layer)}"
                method_names.append(name)
                method_entries.append(
                    f"  - {{ kind: transformer, name: {name}, run_name: {run_name}, "
                    f"label: \"{label}\", mode: {mode}, ckpt_select: latest, "
                    f"embedding_pool: mean, embed_source: {source}, embed_layer: {layer}, "
                    f"checkpoint_dir: {ckpt_dir} }}"
                )

    method_entries.append(
        "  - { kind: mpl_best, name: mpl_best, label: \"MPL (Best)\", "
        "filters: { lesion: 'None', mode: Online, steps: '500000' } }"
    )
    method_names.append("mpl_best")

    methods_block = "\n".join(method_entries)
    method_list_block = "\n".join(f"      - {n}" for n in method_names)

    yaml_text = dedent(
        """\
        # AUTO-GENERATED by scripts/build_probing_robustness_config.py — do not edit by hand.
        # Probe-robustness sweep: per checkpoint, sweeps (embed_source, embed_layer).
        run_name: probe_robustness_v1
        output_dir: outputs/analysis
        rule_data_root: src/data/osf_gq2hj/analysis/data
        device: cuda

        methods:
        {methods}

        analyses:
          - kind: probing
            methods:
        {method_list}
            mpl_method: mpl_best
            acquired_method: mpl
            # Point at the headline study_v1 rule_acquisition output instead of
            # this sweep's run dir (which has no rule_acquisition of its own).
            # Change this if your rule_acquisition was run under a different name.
            acquired_dir: outputs/analysis/study_v1/rule_acquisition
            primitives: [MemorizeAll, Memorize, AntiUnify, Recurse, Variable, Delete]
            n_folds: 5
            n_perm: 50           # smaller null on a wide sweep; bump to 200 for the headline run
            label_aggregation: majority
            majority_threshold: 0.5
            embedding_pool: mean
            n_io_shown: 11
            order: 1
            surface_baseline: true
            conditional: false   # off — speeds up wide sweep; flip on for the headline run
        """
    ).format(methods=methods_block, method_list=method_list_block)

    out_path = Path(__file__).resolve().parent.parent / "src/analysis/configs/probing_robustness.yaml"
    out_path.write_text(yaml_text)
    print(f"Wrote {out_path}  ({len(method_names)} methods, "
          f"{len(CKPTS)} ckpts × {len(SOURCES)} sources × {len(LAYERS)} layers + mpl_best)")


if __name__ == "__main__":
    main()
